Repository TAVE-WEBSITE/TAVE-WEBSITE-BE, pull requests merged in 2024-12, with the labels that each got.

#38 [Feat] 프로젝트 crud 구현
  src/main/java/com/tave/tavewebsite/domain/project/controller/ProjectController.java
  src/main/java/com/tave/tavewebsite/domain/project/controller/SuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/project/dto/request/ProjectRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/project/dto/response/ProjectResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/project/entity/Project.java
  src/main/java/com/tave/tavewebsite/domain/project/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/project/exception/ProjectNotFoundException.java
  src/main/java/com/tave/tavewebsite/domain/project/repository/CustomProjectRepository.java
  src/main/java/com/tave/tavewebsite/domain/project/repository/CustomProjectRepositoryImpl.java
  src/main/java/com/tave/tavewebsite/domain/project/repository/ProjectRepository.java
  src/main/java/com/tave/tavewebsite/domain/project/service/ProjectService.java
  src/main/java/com/tave/tavewebsite/global/common/FieldType.java
Labels: feat

#42 [feat] 승인된 운영진 조회
  src/main/java/com/tave/tavewebsite/domain/member/controller/AdminController.java
  src/main/java/com/tave/tavewebsite/domain/member/controller/ManagerController.java
  src/main/java/com/tave/tavewebsite/domain/member/dto/response/AuthorizedManagerResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/member/service/MemberService.java
Labels: feat

#45 [Feat] 토큰 저장 위치 변경
  src/main/java/com/tave/tavewebsite/domain/member/controller/AdminController.java
  src/main/java/com/tave/tavewebsite/domain/member/controller/AuthController.java
  src/main/java/com/tave/tavewebsite/domain/member/controller/ManagerController.java
  src/main/java/com/tave/tavewebsite/domain/member/dto/request/RefreshTokenRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/member/dto/response/RefreshResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/member/dto/response/SignInResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/member/service/AdminService.java
  src/main/java/com/tave/tavewebsite/domain/member/service/AuthService.java
  src/main/java/com/tave/tavewebsite/domain/member/service/MemberService.java
  src/main/java/com/tave/tavewebsite/global/security/config/Config.java
  src/main/java/com/tave/tavewebsite/global/security/exception/CustomAuthenticationEntryPoint.java
  src/main/java/com/tave/tavewebsite/global/security/exception/JwtErrorMessage.java
  src/main/java/com/tave/tavewebsite/global/security/exception/JwtValidException.java
  src/main/java/com/tave/tavewebsite/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/tave/tavewebsite/global/security/utils/CookieUtil.java
Labels: enhancement, feat, refactor, fix

#44 [feat] 운영진 강제 탈퇴 처리 기능 구현
  src/main/java/com/tave/tavewebsite/domain/member/controller/AdminController.java
  src/main/java/com/tave/tavewebsite/domain/member/controller/SuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/member/dto/response/AuthorizedManagerResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/member/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/member/exception/NotManagerAccessException.java
  src/main/java/com/tave/tavewebsite/domain/member/service/AdminService.java
  src/main/java/com/tave/tavewebsite/domain/project/controller/ProjectController.java
Labels: feat

#48 [fix] 승인 대기, 완료 운영진 조회
  src/main/java/com/tave/tavewebsite/domain/member/controller/AdminController.java
  src/main/java/com/tave/tavewebsite/domain/member/controller/SuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/member/dto/response/AuthorizedManagerResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/member/dto/response/ManagerResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/member/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/member/exception/InvalidStatusValueExcception.java
  src/main/java/com/tave/tavewebsite/domain/member/memberRepository/MemberRepository.java
  src/main/java/com/tave/tavewebsite/domain/member/service/AdminService.java
Labels: fix

#52 [feat] 대기 운영진 승인/거절
  src/main/java/com/tave/tavewebsite/domain/member/controller/AdminController.java
  src/main/java/com/tave/tavewebsite/domain/member/controller/SuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/member/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/member/exception/NotFoundUnauthorizedManager.java
  src/main/java/com/tave/tavewebsite/domain/member/service/AdminService.java
Labels: feat

#51 [Fix] 로그아웃 로직 수정
  src/main/java/com/tave/tavewebsite/domain/member/controller/AuthController.java
  src/main/java/com/tave/tavewebsite/domain/member/service/AuthService.java
  src/main/java/com/tave/tavewebsite/global/redis/utils/RedisUtil.java
  src/main/java/com/tave/tavewebsite/global/security/utils/CookieUtil.java
Labels: fix
