Repository TAVE-WEBSITE/TAVE-WEBSITE-BE, pull requests merged in 2024-11, with the labels that each got.

#12 [Feat] Global Exception 구현
  src/main/java/com/tave/tavewebsite/global/exception/BaseErrorException.java
  src/main/java/com/tave/tavewebsite/global/exception/GlobalExceptionHandler.java
  src/main/java/com/tave/tavewebsite/global/exception/Response/ExceptionResponse.java
Labels: feat

#16 [Feat] Global SuccessResponse 구현
  src/main/java/com/tave/tavewebsite/domain/project/entity/Project.java
  src/main/java/com/tave/tavewebsite/domain/review/entity/Review.java
  src/main/java/com/tave/tavewebsite/domain/study/entity/FieldType.java
  src/main/java/com/tave/tavewebsite/domain/study/entity/Study.java
  src/main/java/com/tave/tavewebsite/global/common/FieldType.java
  src/main/java/com/tave/tavewebsite/global/success/SuccessResponse.java
  src/main/java/com/tave/tavewebsite/global/success/SuccessResponseStatus.java
  src/main/java/com/tave/tavewebsite/global/success/SuccessStatus.java
Labels: feat, refactor

#14 [Chore] cicd 구축
  .github/workflows/gradle.yml
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/com/tave/tavewebsite/global/config/S3Config.java
  src/main/resources/application.yml
Labels: enhancement

#23 [Feat] s3 이미지 crud 구현
  src/main/java/com/tave/tavewebsite/global/exception/GlobalExceptionHandler.java
  src/main/java/com/tave/tavewebsite/global/s3/config/S3Config.java
  src/main/java/com/tave/tavewebsite/global/s3/exception/S3ErrorException.java
  src/main/java/com/tave/tavewebsite/global/s3/exception/S3ErrorMessage.java
  src/main/java/com/tave/tavewebsite/global/s3/service/S3Service.java
  src/main/resources/application.yml
Labels: feat

#24 [Feat] 회원가입 구현
  build.gradle
  src/main/java/com/tave/tavewebsite/domain/member/controller/ManagerController.java
  src/main/java/com/tave/tavewebsite/domain/member/dto/request/RegisterManagerRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/member/dto/response/CheckNickNameResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/member/dto/response/UnauthorizedManagerResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/member/entity/Member.java
  src/main/java/com/tave/tavewebsite/domain/member/entity/RoleType.java
  src/main/java/com/tave/tavewebsite/domain/member/exception/DuplicateEmailException.java
  src/main/java/com/tave/tavewebsite/domain/member/exception/DuplicateNicknameException.java
  src/main/java/com/tave/tavewebsite/domain/member/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/member/exception/NotFoundMemberException.java
  src/main/java/com/tave/tavewebsite/domain/member/memberRepository/MemberRepository.java
  src/main/java/com/tave/tavewebsite/domain/member/service/MemberService.java
  src/main/java/com/tave/tavewebsite/domain/session/entity/repository/SessionRepository.java
  src/main/java/com/tave/tavewebsite/global/exception/GlobalExceptionHandler.java
  src/main/java/com/tave/tavewebsite/global/mail/config/MailConfig.java
  src/main/java/com/tave/tavewebsite/global/mail/dto/MailResponseDto.java
  src/main/java/com/tave/tavewebsite/global/mail/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/global/mail/exception/FailCreateMailException.java
  src/main/java/com/tave/tavewebsite/global/mail/exception/FailMailSendException.java
  src/main/java/com/tave/tavewebsite/global/mail/service/MailService.java
  src/main/resources/application.yml
Labels: feat

#36 [Feat] 이메일 인증 구현
  build.gradle
  src/main/java/com/tave/tavewebsite/domain/member/controller/AuthController.java
  src/main/java/com/tave/tavewebsite/domain/member/controller/ManagerController.java
  src/main/java/com/tave/tavewebsite/domain/member/dto/request/ResetPasswordReq.java
  src/main/java/com/tave/tavewebsite/domain/member/dto/request/ValidateEmailReq.java
  src/main/java/com/tave/tavewebsite/domain/member/entity/Member.java
  src/main/java/com/tave/tavewebsite/domain/member/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/member/exception/ExpiredNumberException.java
  src/main/java/com/tave/tavewebsite/domain/member/exception/NotMatchedNumberException.java
  src/main/java/com/tave/tavewebsite/domain/member/exception/NotMatchedPassword.java
  src/main/java/com/tave/tavewebsite/domain/member/service/MemberService.java
  src/main/java/com/tave/tavewebsite/global/mail/service/MailService.java
  src/main/java/com/tave/tavewebsite/global/redis/utils/RedisUtil.java
  src/main/resources/templates/email-verification.html
Labels: feat, fix

#31 [Feat] 후기 비지니스 로직 개발
  src/main/java/com/tave/tavewebsite/domain/member/controller/ManagerController.java
  src/main/java/com/tave/tavewebsite/domain/member/dto/response/CheckNickNameResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/review/controller/ReviewController.java
  src/main/java/com/tave/tavewebsite/domain/review/controller/SuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/review/dto/request/ReviewRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/review/entity/Review.java
  src/main/java/com/tave/tavewebsite/domain/review/exception/ErrorMessgae.java
  src/main/java/com/tave/tavewebsite/domain/review/exception/ReviewNotFoundException.java
  src/main/java/com/tave/tavewebsite/domain/review/mapper/ReviewMapper.java
  src/main/java/com/tave/tavewebsite/domain/review/repository/ReviewRepository.java
  src/main/java/com/tave/tavewebsite/domain/review/service/ReviewService.java
  src/main/java/com/tave/tavewebsite/global/security/config/Config.java
Labels: feat

#37 [Feat] 스터디 crud 구현
  build.gradle
  src/main/java/com/tave/tavewebsite/TaveWebsiteApplication.java
  src/main/java/com/tave/tavewebsite/domain/study/controller/StudyController.java
  src/main/java/com/tave/tavewebsite/domain/study/dto/StudyRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/study/dto/StudyResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/study/entity/Study.java
  src/main/java/com/tave/tavewebsite/domain/study/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/study/exception/NotFoundStudy.java
  src/main/java/com/tave/tavewebsite/domain/study/repository/CustomStudyRepository.java
  src/main/java/com/tave/tavewebsite/domain/study/repository/CustomStudyRepositoryImpl.java
  src/main/java/com/tave/tavewebsite/domain/study/repository/StudyRepository.java
  src/main/java/com/tave/tavewebsite/domain/study/service/StudyService.java
  src/main/java/com/tave/tavewebsite/global/common/SwaggerConfig.java
  src/main/java/com/tave/tavewebsite/global/security/exception/CustomAuthenticationEntryPoint.java
  src/main/resources/application.yml
  src/test/java/com/tave/tavewebsite/domain/study/entity/StudyTest.java
  src/test/java/com/tave/tavewebsite/domain/study/service/StudyServiceTest.java
Labels: feat, fix
