Repository TAVE-WEBSITE/TAVE-WEBSITE-BE, pull requests merged in 2025-01, with the labels that each got.

#56 [Feat] Hsitory 엔티티 수정 및 Resume 엔티티 생성
  src/main/java/com/tave/tavewebsite/domain/history/controller/HistorySuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/history/controller/ManagerHistoryController.java
  src/main/java/com/tave/tavewebsite/domain/history/dto/request/HistoryRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/history/dto/response/HistoryResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/history/entity/History.java
  src/main/java/com/tave/tavewebsite/domain/member/entity/Member.java
  src/main/java/com/tave/tavewebsite/domain/member/entity/Sex.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/LanguageLevel.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/Level.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/Question.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/TimeSlot.java
Labels: feat, fix

#58 Feat/#57/이미지 확장자 변경
  build.gradle
  src/main/java/com/tave/tavewebsite/global/s3/exception/S3ErrorException.java
  src/main/java/com/tave/tavewebsite/global/s3/exception/S3ErrorMessage.java
  src/main/java/com/tave/tavewebsite/global/s3/service/S3Service.java
Labels: enhancement, feat

#60 [Fix] 이력 반환 형식 변경
  src/main/java/com/tave/tavewebsite/domain/history/controller/ManagerHistoryController.java
  src/main/java/com/tave/tavewebsite/domain/history/controller/NormalHistoryController.java
  src/main/java/com/tave/tavewebsite/domain/history/dto/request/HistoryRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/history/dto/response/HistoryResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/history/dto/response/HistoryResponseDtoList.java
  src/main/java/com/tave/tavewebsite/domain/history/repository/HistoryRepository.java
  src/main/java/com/tave/tavewebsite/domain/history/service/HistoryService.java
Labels: fix

#63 Feat #63 aws cloudwatch 적용
  .github/workflows/CI-CD.yml
  docker-compose.yml
Labels: feat, fix

#67 [Feat]AWS Auto Scaling Group 적용 및 CI/CD 워크 플로우 변경
  .github/workflows/CI-CD.yml
  docker-compose.yml
  src/main/java/com/tave/tavewebsite/global/common/controller/HealthCheckController.java
Labels: enhancement, feat, fix

#66 [Feat] Redis를 클라우드로 사용하도록 구현
  src/main/java/com/tave/tavewebsite/global/redis/config/RedisConfig.java
  src/main/java/com/tave/tavewebsite/global/redis/entity/RedisProperties.java
  src/main/resources/application.yml
Labels: feat
