Repository TAVE-WEBSITE/TAVE-WEBSITE-BE, pull requests merged in 2025-02, with the labels that each got.

#72 [fix] 프로젝트 엔티티 수정
  src/main/java/com/tave/tavewebsite/domain/project/dto/response/ProjectResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/project/entity/Project.java
Labels: fix

#73 [Fix] 스터디 로직 수정
  src/main/java/com/tave/tavewebsite/domain/study/controller/StudyController.java
  src/test/java/com/tave/tavewebsite/domain/study/service/StudyServiceTest.java
Labels: feat, fix

#75 [fix] cors 주소에 도메인 허가
  src/main/java/com/tave/tavewebsite/global/security/config/Config.java
Labels: fix

#77 Fix/#76/분야 별 반환 문자열 변경
  src/main/java/com/tave/tavewebsite/domain/review/dto/response/ReviewResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/review/mapper/ReviewMapper.java
  src/main/java/com/tave/tavewebsite/global/common/FieldType.java
Labels: fix

#79 Feat/#78/신규 지원 이메일 알림
  src/main/java/com/tave/tavewebsite/domain/emailnotification/controller/EmailNotificationSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/controller/NormalEmailNotificationController.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/dto/request/EmailNotificationRequeestDto.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/entity/EmailNotification.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/entity/EmailStatus.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/repository/EmailNotificationRepository.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/service/EmailNotificationService.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/util/EmailNotificationMapper.java
Labels: feat
