Repository TAVE-WEBSITE/TAVE-WEBSITE-BE, pull requests merged in 2025-03, with the labels that each got.

#81 [Feat]: 신규 회원 모집 관련 엔티티 코드 수정
  src/main/java/com/tave/tavewebsite/domain/question/entity/Question.java
  src/main/java/com/tave/tavewebsite/domain/question/entity/QuestionType.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/ResumeQuestion.java
Labels: refactor, feat

#85 [Fix] 이메일 인증에 불필요한 필드 삭제
  src/main/java/com/tave/tavewebsite/domain/member/dto/request/ValidateEmailReq.java
  src/main/java/com/tave/tavewebsite/domain/member/service/MemberService.java
Labels: fix

#91 [fix] 회원가입 및 비밀번호 재설정 API 통합
  src/main/java/com/tave/tavewebsite/domain/member/controller/ManagerController.java
  src/main/java/com/tave/tavewebsite/domain/member/service/MemberService.java
Labels: fix

#92 [Feat] 프로그래밍 실력 관련 crud 작업
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/controller/ProgramingLanguageController.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/controller/ProgramingLanguageSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/dto/request/LanguageLevelRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/dto/response/LanguageLevelResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/entity/LanguageLevel.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/entity/ProgramingLanguage.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/repository/LanguageLevelRepository.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/repository/ProgramingLanguageRepository.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/service/ProgramingLanguageService.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/util/LanguageLevelMapper.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/Level.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java
  src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeRepository.java
Labels: feat

#93 [Feat] 면접 기능 구현
  src/main/java/com/tave/tavewebsite/domain/resume/dto/timeslot/TimeSlotReqDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/timeslot/TimeSlotResDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/TimeSlot.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/NotValidTimeException.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/ResumeNotFoundException.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/UnauthorizedResumeException.java
  src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeRepository.java
  src/main/java/com/tave/tavewebsite/domain/resume/repository/TimeSlotRepository.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/TimeSlotService.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/TimeSlotServiceImpl.java
  src/main/java/com/tave/tavewebsite/global/security/exception/AuthorizedException.java
  src/main/java/com/tave/tavewebsite/global/security/exception/ErrorType.java
  src/main/java/com/tave/tavewebsite/global/security/utils/SecurityUtils.java
  src/test/java/com/tave/tavewebsite/domain/resume/service/TimeSlotServiceImplTest.java
Labels: test, feat

#95 [feat] 지원서 개인정보 crud
  src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/request/PersonalInfoRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/response/PersonalInfoResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/InvalidFieldException.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/MemberNotFoundException.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/ResumeNotFoundException.java
  src/main/java/com/tave/tavewebsite/domain/resume/mapper/ResumeMapper.java
  src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeRepository.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
Labels: feat

#98 [fix] 언어 레벨 엔드포인트 각각에 필요한 권한에 맞게 수정
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/controller/ProgramingLanguageController.java
Labels: fix

#99 [fix] 지원서 개인정보 입력 api 엔드포인트 일반 회원으로 변경
  src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java
Labels: fix

#102 [fix] 변경된 디자인에 맞추어 반환 형식 변경
  src/main/java/com/tave/tavewebsite/domain/history/dto/response/HistoryResponseDto.java
Labels: fix

#103 [Fix] RequestBody를 받기 위한 메서드 유형 수정
  src/main/java/com/tave/tavewebsite/domain/member/controller/ManagerController.java
Labels: fix
