Repository TAVE-WEBSITE/TAVE-WEBSITE-BE, pull requests merged in 2025-05, with the labels that each got.

#117 [fix] 승인 대기/완료 운영진 조회 API 방식 수정
  src/main/java/com/tave/tavewebsite/domain/member/controller/AdminController.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/response/CreatePersonalInfoResponse.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
Labels: fix, refactor

#115 [feat] 이력서 분야별 질문 생성
  src/main/java/com/tave/tavewebsite/domain/member/entity/Member.java
  src/main/java/com/tave/tavewebsite/global/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/tave/tavewebsite/global/security/utils/JwtTokenProvider.java
Labels: refactor, feat

#128 [Bug] Resume 삭제 시 FK 제약 오류 발생
  src/main/java/com/tave/tavewebsite/domain/member/entity/Member.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java
Labels: fix

#121 [feat] 이력서 페이지별 조회
  src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeAnswerTempController.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeQuestionController.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/request/ResumeAnswerTempDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/request/ResumeAnswerTempWrapper.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/request/TempPersonalInfoDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/InvalidPageNumberException.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/TempNotFoundException.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/TempParseFailedException.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/TempSaveFailedException.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/TempSerializeFailedException.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeAnswerTempService.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeQuestionService.java
Labels: feat

#131 Feat 면접 설정 api 구현
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/SuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/interviewplace/controller/InterviewPlaceController.java
  src/main/java/com/tave/tavewebsite/domain/interviewplace/dto/request/InterviewPlaceSaveDto.java
  src/main/java/com/tave/tavewebsite/domain/interviewplace/dto/response/InterviewPlaceResponse.java
  src/main/java/com/tave/tavewebsite/domain/interviewplace/entity/InterviewPlace.java
  src/main/java/com/tave/tavewebsite/domain/interviewplace/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/interviewplace/exception/NotFoundInterviewPlaceException.java
  src/main/java/com/tave/tavewebsite/domain/interviewplace/repository/InterviewPlaceRepository.java
  src/main/java/com/tave/tavewebsite/domain/interviewplace/service/InterviewPlaceService.java
Labels: feat

#133 fix: 전체 개인정보 조회, memberId로 개인정보 수정
  src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/response/PersonalInfoResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
Labels: fix

#136 fix: 지원서 수정
  src/main/java/com/tave/tavewebsite/domain/question/dto/request/QuestionSaveRequest.java
  src/main/java/com/tave/tavewebsite/domain/question/dto/request/QuestionUpdateRequest.java
  src/main/java/com/tave/tavewebsite/domain/question/dto/response/QuestionDetailsResponse.java
  src/main/java/com/tave/tavewebsite/domain/question/entity/Question.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/response/CreatePersonalInfoResponse.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/response/DetailResumeQuestionResponse.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/AnswerType.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/ResumeQuestion.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/ResumeState.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/AlreadySubmittedResumeException.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
Labels: refactor

#139 [Feat] 서류 평가 api 기능 구현
  src/main/java/com/tave/tavewebsite/domain/member/entity/Member.java
  src/main/java/com/tave/tavewebsite/domain/member/entity/RoleType.java
  src/main/java/com/tave/tavewebsite/domain/member/exception/AlreadyExistsResumeException.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeEvaluateController.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeEvaluateSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/request/ResumeEvaluateReqDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/response/ResumeEvaluateResDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/response/ResumeResDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/EvaluationStatus.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/ResumeEvaluation.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeEvaluationRepository.java
  src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeRepository.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeEvaluateService.java
  src/main/java/com/tave/tavewebsite/global/security/config/Config.java
  src/main/java/com/tave/tavewebsite/global/security/entity/CustomUserDetails.java
  src/main/java/com/tave/tavewebsite/global/security/service/CustomUserDetailsService.java
  src/main/java/com/tave/tavewebsite/global/security/utils/JwtTokenProvider.java
  src/main/java/com/tave/tavewebsite/global/security/utils/SecurityUtils.java
Labels: fix, refactor, feat

#143 feat: 최종 합격 안내 설정 기능 구현
  src/main/java/com/tave/tavewebsite/domain/finalpass/controller/FinalPassController.java
  src/main/java/com/tave/tavewebsite/domain/finalpass/controller/FinalPassSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/finalpass/dto/request/FinalPassRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/finalpass/dto/response/FinalPassResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/finalpass/entity/FinalPass.java
  src/main/java/com/tave/tavewebsite/domain/finalpass/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/finalpass/exception/FinalPassNotFoundException.java
  src/main/java/com/tave/tavewebsite/domain/finalpass/mapper/FinalPassMapper.java
  src/main/java/com/tave/tavewebsite/domain/finalpass/repository/FinalPassRepository.java
  src/main/java/com/tave/tavewebsite/domain/finalpass/service/FinalPassService.java
Labels: feat
