Repository TAVE-WEBSITE/TAVE-WEBSITE-BE, pull requests merged in 2025-04, with the labels that each got.

#105 fix: 회원가입 시 이메일 인증 재수정
  src/main/java/com/tave/tavewebsite/domain/member/controller/ManagerController.java
  src/main/java/com/tave/tavewebsite/domain/member/service/MemberService.java
  src/test/java/com/tave/tavewebsite/global/s3/service/S3ServiceTest.java
Labels: fix, test

#100 [feat] 소셜주소 crud 기능 구현
  src/main/java/com/tave/tavewebsite/domain/resume/controller/SocialLinksController.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/SocialLinksSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/request/SocialLinksRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/response/SocialLinksResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/InvalidFieldException.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/SocialLinkNotFoundException.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/SocialLinksService.java
  src/main/java/com/tave/tavewebsite/global/s3/service/S3Service.java
Labels: feat

#104 [fix] 일반 회원가입 패키지 위치 수정
  src/main/java/com/tave/tavewebsite/domain/member/controller/AuthController.java
  src/main/java/com/tave/tavewebsite/domain/member/controller/ManagerController.java
Labels: fix

#107 [feat] 일반회원 비밀번호 찾기
  src/main/java/com/tave/tavewebsite/domain/member/controller/AuthController.java
  src/main/java/com/tave/tavewebsite/domain/member/controller/MemberSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/member/dto/request/ResetNormalPasswordRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/member/dto/request/ResetPasswordVerifyRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/member/service/MemberService.java
Labels: feat

#108 [fix] webp로 파일 형식 변환시 파일명 생성 오류
  src/main/java/com/tave/tavewebsite/domain/resume/controller/TimeSlotController.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/TimeSlotSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/timeslot/TimeSlotReqDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/TimeSlot.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/TimeSlotService.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/TimeSlotServiceImpl.java
  src/main/java/com/tave/tavewebsite/global/s3/service/S3Service.java
  src/test/java/com/tave/tavewebsite/domain/resume/service/TimeSlotServiceImplTest.java
  src/test/java/com/tave/tavewebsite/global/s3/service/S3ServiceTest.java
Labels: fix, feat

#109 [Feat] 지원서 질문 관리
  src/main/java/com/tave/tavewebsite/domain/question/controller/QuestionController.java
  src/main/java/com/tave/tavewebsite/domain/question/controller/SuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/question/dto/request/QuestionDetailRequest.java
  src/main/java/com/tave/tavewebsite/domain/question/dto/request/QuestionSaveRequest.java
  src/main/java/com/tave/tavewebsite/domain/question/dto/request/QuestionUpdateRequest.java
  src/main/java/com/tave/tavewebsite/domain/question/dto/response/QuestionDetailsResponse.java
  src/main/java/com/tave/tavewebsite/domain/question/entity/Question.java
  src/main/java/com/tave/tavewebsite/domain/question/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/question/exception/QuestionNotFoundException.java
  src/main/java/com/tave/tavewebsite/domain/question/repository/QuestionRepository.java
  src/main/java/com/tave/tavewebsite/domain/question/service/QuestionService.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/request/ResumeQuestionUpdateRequest.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/response/DetailResumeQuestionResponse.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/response/ResumeQuestionResponse.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/ResumeQuestion.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/ResumeQuestionNotMatchResumeException.java
  src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeQuestionJdbcRepository.java
  src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeQuestionRepository.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeQuestionService.java
  src/main/java/com/tave/tavewebsite/global/common/FieldType.java
  src/main/java/com/tave/tavewebsite/global/security/config/Config.java
  src/main/resources/application.yml
  src/main/resources/logback.xml
Labels: feat

#111 [Feat] 이력서 생성시 프로그래밍 언어 초기화 작업
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/controller/ProgramingLanguageAdminController.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/controller/ProgramingLanguageController.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/controller/ProgramingLanguageSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/dto/request/ProgramingLanguageRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/dto/request/ProgrammingLanguageByFieldRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/dto/response/ProgrammingLanguageResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/entity/ProgramingLanguage.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/exception/LanguageErrorException.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/exception/ProgrammingLanguageErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/repository/ProgramingLanguageRepository.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/service/ProgramingLanguageAdminService.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/service/ProgramingLanguageService.java
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/util/LanguageLevelMapper.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
  src/main/java/com/tave/tavewebsite/global/common/FieldType.java
Labels: feat

#113 [fix] 필드타입 수정
  src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/FieldTypeInvalidException.java
  src/main/java/com/tave/tavewebsite/domain/resume/mapper/ResumeMapper.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
Labels: fix, refactor
