Repository TAVE-WEBSITE/TAVE-WEBSITE-BE, pull requests merged in 2025-06, with the labels that each got.

#142 [Feat] 이메일 대량 발송 기능 구현
  build.gradle
  src/main/java/com/tave/tavewebsite/domain/emailnotification/batch/config/EmailNotificationBatchConfig.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/batch/exception/EmailNotificationBatchErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/batch/exception/EmailNotificationBatchException.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/batch/reader/EmailReaderConfig.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/batch/reader/IdRangePartitioner.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/batch/scheduler/EmailBatchScheduler.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/batch/writer/EmailWriterConfig.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/controller/EmailNotificationSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/controller/NormalEmailNotificationController.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/dto/response/EmailNotificationApplyResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/entity/EmailNotification.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/repository/EmailNotificationRepository.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/service/EmailNotificationService.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/util/EmailNotificationMapper.java
  src/main/java/com/tave/tavewebsite/global/mail/config/SESMailConfig.java
  src/main/java/com/tave/tavewebsite/global/mail/service/MailService.java
  src/main/java/com/tave/tavewebsite/global/mail/service/SESMailService.java
  src/main/java/com/tave/tavewebsite/global/mail/util/SESMailUtil.java
  src/main/java/com/tave/tavewebsite/global/redis/config/RedisShedLockConfig.java
  src/main/resources/application.yml
Labels: feat

#146 [Fix] 질문 api 수정
  src/main/java/com/tave/tavewebsite/domain/member/dto/request/RegisterManagerRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/member/entity/JobType.java
  src/main/java/com/tave/tavewebsite/domain/member/entity/Member.java
  src/main/java/com/tave/tavewebsite/domain/question/controller/QuestionController.java
  src/main/java/com/tave/tavewebsite/domain/question/controller/SuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/question/dto/request/QuestionSaveRequest.java
  src/main/java/com/tave/tavewebsite/domain/question/dto/request/QuestionSwapRequest.java
  src/main/java/com/tave/tavewebsite/domain/question/dto/request/QuestionUpdateRequest.java
  src/main/java/com/tave/tavewebsite/domain/question/entity/Question.java
  src/main/java/com/tave/tavewebsite/domain/question/repository/QuestionRepository.java
  src/main/java/com/tave/tavewebsite/domain/question/service/QuestionService.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/response/DetailResumeQuestionResponse.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/ResumeQuestion.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/AnswerTextLengthOverException.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeQuestionService.java
Labels: feat

#154 [feat] BulkInsert SQL에 answer_type과 text_length 추가
  src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeQuestionJdbcRepository.java
Labels: feat

#158 [Fix] 면접 설정 기능 요구사항 반영
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/InterviewFinalController.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/SuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/dto/InterviewFinalConvertDto.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/dto/InterviewFinalSaveDto.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/dto/response/InterviewFinalDetailDto.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/dto/response/InterviewFinalForMemberDto.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/entity/InterviewFinal.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/exception/NotFoundInterviewFinalByMemberIdException.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/mapper/InterviewFinalMapper.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/repository/InterviewFinalJdbcRepository.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/repository/InterviewFinalRepository.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/service/InterviewExcelService.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/service/InterviewGetService.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/usecase/InterviewFinalUseCase.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/utils/ExcelUtils.java
  src/main/java/com/tave/tavewebsite/domain/interviewplace/controller/InterviewPlaceController.java
  src/main/java/com/tave/tavewebsite/domain/interviewplace/dto/request/InterviewPlaceSaveDto.java
  src/main/java/com/tave/tavewebsite/domain/interviewplace/dto/response/InterviewPlaceDetailDto.java
  src/main/java/com/tave/tavewebsite/domain/interviewplace/dto/response/InterviewPlaceResponse.java
  src/main/java/com/tave/tavewebsite/domain/interviewplace/entity/InterviewPlace.java
  src/main/java/com/tave/tavewebsite/domain/interviewplace/repository/InterviewPlaceRepository.java
  src/main/java/com/tave/tavewebsite/domain/interviewplace/service/InterviewPlaceService.java
  src/main/java/com/tave/tavewebsite/domain/member/memberRepository/MemberRepository.java
  src/main/java/com/tave/tavewebsite/domain/member/service/MemberService.java
  src/main/java/com/tave/tavewebsite/domain/question/dto/request/QuestionSaveRequest.java
  src/main/java/com/tave/tavewebsite/domain/question/entity/Question.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/AdminConfigSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/InterviewTimeController.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/response/InterviewTimeResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/repository/InterviewTimeRepository.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/InterviewTimeService.java
  src/main/java/com/tave/tavewebsite/global/common/Status.java
  src/main/java/com/tave/tavewebsite/global/security/CurrentMember.java
Labels: fix, feat

#161 [Feat] 마이페이지 기능 개발
  src/main/java/com/tave/tavewebsite/domain/applicant/history/controller/ApplicantHistoryController.java
  src/main/java/com/tave/tavewebsite/domain/applicant/history/controller/ApplicantHistorySuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/applicant/history/dto/request/ApplicantHistoryPatchRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/applicant/history/dto/request/ApplicantHistoryPostRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/applicant/history/dto/response/ApplicantHistoryResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/applicant/history/entity/ApplicantHistory.java
  src/main/java/com/tave/tavewebsite/domain/applicant/history/entity/ApplicationStatus.java
  src/main/java/com/tave/tavewebsite/domain/applicant/history/exception/ApplicantHistoryErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/applicant/history/exception/ApplicantHistoryException.java
  src/main/java/com/tave/tavewebsite/domain/applicant/history/repository/ApplicantHistoryRepository.java
  src/main/java/com/tave/tavewebsite/domain/applicant/history/service/ApplicantHistoryService.java
  src/main/java/com/tave/tavewebsite/domain/applicant/history/util/ApplicantHistoryMapper.java
  src/main/java/com/tave/tavewebsite/domain/member/entity/Member.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/request/PersonalInfoCreateRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java
  src/main/java/com/tave/tavewebsite/domain/resume/mapper/ResumeMapper.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
Labels: feat

#156 feat: 지원서 페이지별 임시저장 기능 구현
  src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeAnswerTempController.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/SocialLinksSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/request/PersonalInfoRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/request/ResumeAnswerTempWrapper.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/request/ResumeReqDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/wrapper/ResumeTempWrapper.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/TempReadFailedException.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeAnswerTempService.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/SocialLinksService.java
Labels: feat

#170 [feat] 임시 저장 형식에 language levels 필드 추가
  src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeAnswerTempController.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/request/ResumeReqDto.java
Labels: feat

#176 [Feat] 가입 승인 거절 메일 기능 개발
  src/main/java/com/tave/tavewebsite/domain/member/service/AdminService.java
  src/main/java/com/tave/tavewebsite/global/mail/service/SESMailService.java
Labels: feat

#178 feat: 포트폴리오 업로드
  src/main/java/com/tave/tavewebsite/domain/programinglaunguage/dto/request/LanguageLevelRequestDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/SocialLinksController.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeAnswerTempService.java
Labels: feat

#182 fix: 지원서 질문 중복 생성 방지
  src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java
  src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeQuestionRepository.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
Labels: fix

#183 Feat: 이메일 템플릿 제작 및 전송
  src/main/java/com/tave/tavewebsite/domain/member/controller/AuthController.java
  src/main/java/com/tave/tavewebsite/domain/member/controller/MemberSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/member/service/MemberService.java
  src/main/java/com/tave/tavewebsite/global/mail/service/SESMailService.java
  src/main/resources/templates/email-verification.html
Labels: refactor, feat

#186 feat: 최종제출 여부 필드 추가
  src/main/java/com/tave/tavewebsite/domain/member/controller/AuthController.java
  src/main/java/com/tave/tavewebsite/domain/member/dto/response/SignInResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/member/service/AuthService.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/ResumeState.java
Labels: refactor, feat

#190 [Feat] TEST-CI-CD.yml 작성
  .github/workflows/TEST-CI-CD.yml
Labels: test, feat
