Repository TAVE-WEBSITE/TAVE-WEBSITE-BE, pull requests merged in 2025-07, with the labels that each got.

#195 [fix] required 필드 추가 및 엔티티에 반영
  src/main/java/com/tave/tavewebsite/domain/question/dto/request/QuestionSaveRequest.java
  src/main/java/com/tave/tavewebsite/domain/question/dto/request/QuestionUpdateRequest.java
  src/main/java/com/tave/tavewebsite/domain/question/dto/response/QuestionDetailsResponse.java
  src/main/java/com/tave/tavewebsite/domain/question/entity/Question.java
Labels: fix, refactor

#200 [Feat] 이력서 삭제 스케쥴러
  src/main/java/com/tave/tavewebsite/domain/applicant/history/controller/ApplicantHistoryController.java
  src/main/java/com/tave/tavewebsite/domain/applicant/history/repository/ApplicantHistoryRepository.java
  src/main/java/com/tave/tavewebsite/domain/applicant/history/service/ApplicantHistoryService.java
  src/main/java/com/tave/tavewebsite/domain/apply/initial/setup/service/ApplyInitialSetupService.java
  src/main/java/com/tave/tavewebsite/domain/resume/batch/controller/RecruitmentBatchSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/batch/controller/RecruitmentEmailBatchController.java
  src/main/java/com/tave/tavewebsite/domain/resume/batch/scheduler/RecruitmentResultScheduler.java
  src/main/java/com/tave/tavewebsite/domain/resume/batch/writer/LastResultWriterConfig.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/EvaluationStatus.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeEvaluateService.java
Labels: fix, feat

#202 fix: 개인 정보 및 질문 생성 트랜잭션 통합으로 롤백 문제 해결
  src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
Labels: fix, refactor

#198 [Feat] 면접가능시간 파악 엑셀 api 구현
  src/main/java/com/tave/tavewebsite/domain/apply/initial/setup/service/ApplyInitialSetupService.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/InterviewExcelController.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/InterviewFinalController.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/dto/S3ExcelFileInputStreamDto.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/service/InterviewExcelService.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/usecase/InterviewExcelUseCase.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/usecase/InterviewFinalUseCase.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/utils/ExcelUtils.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/response/ResumeMemberInfoDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeRepository.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeGetService.java
  src/main/java/com/tave/tavewebsite/global/s3/service/S3DownloadSerivce.java
  src/main/java/com/tave/tavewebsite/global/s3/service/S3Service.java
  src/main/resources/application.yml
  src/test/java/com/tave/tavewebsite/global/s3/service/S3ServiceTest.java
Labels: feat

#207 feat: 소셜 링크 및 포트폴리오 임시저장 기능 수정
  src/main/java/com/tave/tavewebsite/domain/resume/controller/SocialLinksController.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/SocialLinksService.java
Labels: fix, refactor

#208 [Feat] Interveiwfinal 생성 test 기능 추가
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/InterviewFinalController.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/SuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/service/InterviewFinalTestService.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/usecase/InterviewFinalUseCase.java
  src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeRepository.java
Labels: feat

#213 Fix: 이력서 평가 리스트 조회 필터링 기능 수정
  src/main/java/com/tave/tavewebsite/domain/resume/entity/AnswerType.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/ResumeQuestion.java
  src/main/java/com/tave/tavewebsite/global/s3/service/S3Service.java
Labels: refactor, feat

#212 fix: 소셜 링크 및 포트폴리오 DB 저장과 Redis 임시저장 동기화 구현
  src/main/java/com/tave/tavewebsite/domain/resume/service/SocialLinksService.java
Labels: refactor

#217 [Feat] 서류 제출기한 검증 API
  src/main/java/com/tave/tavewebsite/domain/apply/initial/setup/controller/ApplyInitialSetupController.java
  src/main/java/com/tave/tavewebsite/domain/apply/initial/setup/controller/ApplyInitialSetupSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/apply/initial/setup/entity/ApplyInitialSetup.java
  src/main/java/com/tave/tavewebsite/domain/apply/initial/setup/service/ApplyInitialSetupService.java
Labels: feat

#204 feat: 지원서 리스트 조회 기능 및 공통/분야별 응답 DTO 분리 구현
  src/main/java/com/tave/tavewebsite/domain/resume/dto/response/CommonResumeResponse.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/response/ResumeListResponse.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/response/ResumeResponse.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/response/SpecificResumeResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/Resume.java
  src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeRepository.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeQuestionService.java
Labels: feat

#221 [Feat] 면접관 시간표 파일 업로드 및 다운로드 API
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/InterviewExcelController.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/SuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/exception/EmptyFileException.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/exception/IsNotXlsxFileException.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/usecase/InterviewExcelUseCase.java
  src/main/java/com/tave/tavewebsite/global/s3/service/S3DownloadSerivce.java
  src/main/java/com/tave/tavewebsite/global/s3/service/S3Service.java
  src/main/resources/application.yml
  src/test/java/com/tave/tavewebsite/global/s3/service/S3ServiceTest.java
Labels: feat

#173 [Feat] 면접 날짜과시간으로 지원서 조회
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/repository/InterviewFinalRepository.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/service/InterviewGetService.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/InterviewTimeController.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/PersonalInfoController.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeAnswerTempController.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeController.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeEmailController.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeEvaluateController.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeQuestionController.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/SocialLinksController.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/TimeSlotController.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/message/AdminConfigSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/message/PersonalInfoSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/message/ResumeEvaluateSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/message/ResumeSuccessMesssage.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/message/SocialLinksSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/message/TimeSlotSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeRepository.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeQuestionService.java
  src/main/java/com/tave/tavewebsite/domain/resume/usecase/ResumeUseCase.java
Labels: feat

#227 feat: 대시보드 API 구현 및 테스트 완료
  build.gradle
  src/main/java/com/tave/tavewebsite/domain/apply/dashboard/controller/DashboardController.java
  src/main/java/com/tave/tavewebsite/domain/apply/dashboard/controller/DashboardSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/apply/dashboard/dto/DashboardRatioResDto.java
  src/main/java/com/tave/tavewebsite/domain/apply/dashboard/dto/DashboardResDto.java
  src/main/java/com/tave/tavewebsite/domain/apply/dashboard/entity/Dashboard.java
  src/main/java/com/tave/tavewebsite/domain/apply/dashboard/exception/DashboardErrorException.java
  src/main/java/com/tave/tavewebsite/domain/apply/dashboard/exception/DashboardErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/apply/dashboard/repository/DashboardRepository.java
  src/main/java/com/tave/tavewebsite/domain/apply/dashboard/service/DashboardService.java
  src/main/java/com/tave/tavewebsite/domain/apply/initial/setup/service/ApplyInitialSetupService.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeEvaluateController.java
  src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeCustomRepositoryImpl.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
  src/main/java/com/tave/tavewebsite/global/redis/utils/RedisUtil.java
  src/main/java/com/tave/tavewebsite/global/redisson/RedissonConfig.java
  src/main/resources/redisson.yaml
Labels: fix, refactor

#232 [Feat] 이메일 발송 시간 수정
  src/main/java/com/tave/tavewebsite/domain/apply/initial/setup/service/ApplyInitialSetupService.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/batch/scheduler/EmailBatchScheduler.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/service/EmailNotificationService.java
  src/main/java/com/tave/tavewebsite/domain/resume/batch/controller/RecruitmentBatchSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/batch/controller/RecruitmentEmailBatchController.java
  src/main/java/com/tave/tavewebsite/domain/resume/batch/dto/response/RecruitmentResponseDto.java
Labels: feat

#234 Fix: 면접 시간 생성 시 필요한 필드 리팩터링
  src/main/java/com/tave/tavewebsite/domain/apply/dashboard/service/DashboardService.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeEvaluateController.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/request/InterviewTimeReqDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeCustomRepository.java
  src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeCustomRepositoryImpl.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/InterviewTimeService.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeEvaluateService.java
  src/main/java/com/tave/tavewebsite/global/redis/config/RedisConfig.java
  src/main/java/com/tave/tavewebsite/global/redisson/RedissonConfig.java
  src/main/resources/redisson.yaml
Labels: refactor

#239 [Feat]: 신규모집 예약확인 기능 개발
  src/main/java/com/tave/tavewebsite/domain/emailnotification/controller/EmailNotificationSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/controller/NormalEmailNotificationController.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/dto/response/EmailNotificationReservationResponse.java
  src/main/java/com/tave/tavewebsite/domain/emailnotification/service/EmailNotificationService.java
Labels: feat

#244 [fix] 최종합격 안내 조회 수정
  src/main/java/com/tave/tavewebsite/domain/finalpass/controller/FinalPassController.java
  src/main/java/com/tave/tavewebsite/domain/finalpass/entity/FinalPass.java
  src/main/java/com/tave/tavewebsite/domain/finalpass/repository/FinalPassRepository.java
  src/main/java/com/tave/tavewebsite/domain/finalpass/service/FinalPassService.java
Labels: fix

#250 [Fix] Interviewfinal 페이지네이션 수정
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/InterviewFinalController.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/dto/response/InterviewFinalPageDto.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/usecase/InterviewFinalUseCase.java
Labels: fix

#253 Feat: 최종면접 평가 리스트 조회
  src/main/java/com/tave/tavewebsite/domain/apply/initial/setup/service/ApplyInitialSetupService.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/InterviewFinalController.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/SuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/dto/response/InterviewFinalEvaluateResDto.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/dto/response/InterviewFinalResDto.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/repository/InterviewFinalCustomRepository.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/repository/InterviewFinalCustomRepositoryImpl.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/repository/InterviewFinalRepository.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/usecase/InterviewFinalUseCase.java
  src/main/java/com/tave/tavewebsite/domain/resume/entity/EvaluationStatus.java
Labels: fix, refactor, feat

#255 [feat] 로그인 시 resumeId 응답에 추가
  src/main/java/com/tave/tavewebsite/domain/member/dto/response/SignInResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/member/service/AuthService.java
Labels: feat

#246 [feat] 지원자 이름 검색 기능 위해 "name" 파라미터 추가
  src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeEvaluateController.java
  src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeCustomRepository.java
  src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeCustomRepositoryImpl.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeEvaluateService.java
Labels: feat

#257 [feat] 포트폴리오 업로드 api 요청 시 응답 값 수정
  src/main/java/com/tave/tavewebsite/domain/resume/controller/SocialLinksController.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/response/PortfolioUploadResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/ErrorMessage.java
Labels: feat
