Repository TAVE-WEBSITE/TAVE-WEBSITE-BE, pull requests merged in 2025-08, with the labels that each got.

#261 [refactor] 임시저장, 소셜주소 사용자 검증 로직 추가
  src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeAnswerTempController.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/SocialLinksController.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/response/SocialLinksResponseDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/wrapper/ResumeTempWrapper.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/ErrorMessage.java
  src/main/java/com/tave/tavewebsite/domain/resume/exception/InvalidDataOwnerException.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeAnswerTempService.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/SocialLinksService.java
Labels: refactor, feat

#263 [Feat] ResumeTimeSlot과 Member를 함께 조회하는 쿼리 메서드 추가 및 DB fallback 로직에 적용
  src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeRepository.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeAnswerTempService.java
Labels: fix

#265 feat: 대시보드 업데이트 API 구현
  src/main/java/com/tave/tavewebsite/domain/apply/dashboard/controller/DashboardController.java
  src/main/java/com/tave/tavewebsite/domain/apply/dashboard/controller/DashboardSuccessMessage.java
  src/main/java/com/tave/tavewebsite/domain/apply/dashboard/dto/DashboardUpdateDto.java
  src/main/java/com/tave/tavewebsite/domain/apply/dashboard/entity/Dashboard.java
  src/main/java/com/tave/tavewebsite/domain/apply/dashboard/repository/DashboardCustomRepository.java
  src/main/java/com/tave/tavewebsite/domain/apply/dashboard/repository/DashboardCustomRepositoryImpl.java
  src/main/java/com/tave/tavewebsite/domain/apply/dashboard/repository/DashboardRepository.java
  src/main/java/com/tave/tavewebsite/domain/apply/dashboard/service/DashboardService.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/PersonalInfoService.java
Labels: fix, refactor, feat

#269 [fix] 포트폴리오 업로드 시 null 값 허용
  src/main/java/com/tave/tavewebsite/domain/resume/controller/SocialLinksController.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeQuestionService.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/SocialLinksService.java
  src/main/java/com/tave/tavewebsite/global/s3/service/S3Service.java
Labels: fix

#275 [HOTFIX] 포트폴리오 다운로드 구현
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/InterviewExcelController.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/controller/InterviewFinalController.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/dto/S3FileInputStreamDto.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/usecase/InterviewExcelUseCase.java
  src/main/java/com/tave/tavewebsite/domain/interviewfinal/usecase/InterviewFinalUseCase.java
  src/main/java/com/tave/tavewebsite/domain/resume/controller/ResumeController.java
  src/main/java/com/tave/tavewebsite/domain/resume/dto/response/ResumePortfolioDto.java
  src/main/java/com/tave/tavewebsite/domain/resume/repository/ResumeRepository.java
  src/main/java/com/tave/tavewebsite/domain/resume/service/ResumeGetService.java
  src/main/java/com/tave/tavewebsite/domain/resume/usecase/ResumeUseCase.java
  src/main/java/com/tave/tavewebsite/global/s3/service/S3DownloadSerivce.java
Labels: hotfix
